name: Create Storage Account

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configure Terraform
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> .env
        echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> .env
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> .env
        echo "TF_IN_AUTOMATION=true" >> .env

    - name: Initialize Terraform
      run: |
        terraform init

    - name: Apply Terraform configuration
      run: terraform apply -auto-approve