name: Create Storage Account

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    
    - name: Azure login
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Configure Terraform
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> .env
        echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> .env
        echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> .env
        echo "TF_IN_AUTOMATION=true" >> .env

    - name: Initialize Terraform
      run: |
        terraform init

    - name: Apply Terraform configuration
      run: terraform apply -auto-approve