name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Read and Set Environment Variables
        run: |
          DEPLOY=$(jq -r '.deploy' manifest.json)
          ENVIRONMENT=$(jq -r '.environment' manifest.json)
          echo "Deploy: $DEPLOY"
          echo "Environment: $ENVIRONMENT"
          echo "::set-env name=DEPLOY::$DEPLOY"
          echo "::set-env name=ENVIRONMENT::$ENVIRONMENT"

      - name: Deploy if specified
        if: ${{ env.DEPLOY == 'true' }}
        run: |
          echo "Deploying to ${{ env.ENVIRONMENT }} environment"
          # Your deployment steps here